/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import kontrol.koneksi;

/**
 *
 * @author Bayu
 */


public class daftarbarang extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmodel;
    String ekode, enama, ejumlah, emodal, eharga;
    int edittombol = 0;
    int editprompt = 0;
    protected void dataTable() throws SQLException{
        Object[] baris = {"Kode Barang", "Nama Barang", "Jumlah", "Modal", "Harga"};
        tabmodel = new DefaultTableModel(null, baris);
        tbarang.setModel(tabmodel);
        String sql = "select * from barang";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String skdbrg = hasil.getString("kode_barang");
                String snmbrg = hasil.getString("nama_barang");
                int sjum = hasil.getInt("jumlah");
                int smod = hasil.getInt("modal");
                int shar = hasil.getInt("harga");
                tabmodel.addRow(new Object[]{skdbrg, snmbrg, sjum, smod, shar});
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null,
                    "Data Tidak Bisa Ditampilkan"+e);
        }
    
    }
    /**
     * Creates new form daftarbarang
     */
    public void kosong(){
        tfkode.setText("");
        tfnama.setText("");
        tfjumlah.setText("");
        tfmodal.setText("");
        tfharga.setText("");
    }
    
    public daftarbarang() throws SQLException {
        initComponents();
        dataTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbarang = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        tfcarinama = new javax.swing.JTextField();
        jbdelete = new javax.swing.JButton();
        tfcarikd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnedit = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel3 = new javax.swing.JLabel();
        tfkode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfjumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfmodal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfharga = new javax.swing.JTextField();
        jbclear = new javax.swing.JButton();
        jbsave = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        gudang = new javax.swing.JMenu();
        gbaru = new javax.swing.JMenuItem();
        gbarang = new javax.swing.JMenuItem();
        jasa = new javax.swing.JMenu();
        transaksi = new javax.swing.JMenu();
        tbaru = new javax.swing.JMenuItem();
        tdaftar = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Daftar Barang");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(250, 140));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbarang.setBackground(new java.awt.Color(204, 204, 204));
        tbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah", "Modal", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbarang.setRowMargin(3);
        tbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, 679, 503));

        tfcarinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcarinamaActionPerformed(evt);
            }
        });

        jbdelete.setText("Delete");
        jbdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbdeleteActionPerformed(evt);
            }
        });

        tfcarikd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcarikdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("FIND Kode:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("FIND Nama:");

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfcarikd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfcarinama, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnedit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbdelete, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfcarikd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbdelete)
                    .addComponent(jLabel2)
                    .addComponent(tfcarinama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnedit))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jInternalFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jInternalFrame1.setFocusable(false);
        jInternalFrame1.setFrameIcon(null);
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Kode Barang : ");
        jInternalFrame1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 100, -1));

        tfkode.setEditable(false);
        jInternalFrame1.getContentPane().add(tfkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 41, 214, -1));

        jLabel4.setText("Nama Barang : ");
        jInternalFrame1.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, -1, -1));

        tfnama.setEnabled(false);
        jInternalFrame1.getContentPane().add(tfnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 104, 214, -1));

        jLabel5.setText("Jumlah : ");
        jInternalFrame1.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, -1, -1));

        tfjumlah.setEnabled(false);
        jInternalFrame1.getContentPane().add(tfjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 167, 70, -1));

        jLabel6.setText("Modal : ");
        jInternalFrame1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 207, -1, -1));

        tfmodal.setEnabled(false);
        jInternalFrame1.getContentPane().add(tfmodal, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 230, 150, -1));

        jLabel7.setText("Harga : ");
        jInternalFrame1.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 270, -1, -1));

        tfharga.setEnabled(false);
        jInternalFrame1.getContentPane().add(tfharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 293, 150, -1));

        jbclear.setText("Clear");
        jbclear.setEnabled(false);
        jbclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbclearActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 397, 100, -1));

        jbsave.setText("Save");
        jbsave.setEnabled(false);
        jbsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsaveActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jbsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 397, 100, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/GreyBackground.png"))); // NOI18N
        jInternalFrame1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 270, 560));

        getContentPane().add(jInternalFrame1, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 0, 280, 574));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/GreyBackground.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 990, 580));

        gudang.setText("Gudang");

        gbaru.setText("Barang Baru");
        gbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbaruActionPerformed(evt);
            }
        });
        gudang.add(gbaru);

        gbarang.setText("Daftar Barang");
        gbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbarangActionPerformed(evt);
            }
        });
        gudang.add(gbarang);

        menubar.add(gudang);

        jasa.setText("Jasa");
        jasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jasaMouseClicked(evt);
            }
        });
        menubar.add(jasa);

        transaksi.setText("Transaksi");

        tbaru.setText("Transaksi Baru");
        tbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbaruActionPerformed(evt);
            }
        });
        transaksi.add(tbaru);

        tdaftar.setText("Daftar Transaksi");
        tdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdaftarActionPerformed(evt);
            }
        });
        transaksi.add(tdaftar);

        menubar.add(transaksi);

        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        menubar.add(laporan);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbarangActionPerformed
        try {
            new daftarbarang().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_gbarangActionPerformed

    private void gbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbaruActionPerformed
        new inputbarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_gbaruActionPerformed

    private void tdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdaftarActionPerformed
        try {
            new daftartransaksi().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_tdaftarActionPerformed

    private void tbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbaruActionPerformed
        new transaksibaru().setVisible(true);
        dispose();
    }//GEN-LAST:event_tbaruActionPerformed

    private void tfcarikdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcarikdActionPerformed
        String carikode = tfcarikd.getText();
        Object[] baris = {"Kode Barang", "Nama Barang", "Jumlah", "Modal", "Harga"};
        tabmodel = new DefaultTableModel(null, baris);
        tbarang.setModel(tabmodel);
        String sql = "select * from barang where kode_barang LIKE '%"+carikode+"%'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String skdbrg = hasil.getString("kode_barang");
                String snmbrg = hasil.getString("nama_barang");
                int sjum = hasil.getInt("jumlah");
                int smod = hasil.getInt("modal");
                int shar = hasil.getInt("harga");
                tabmodel.addRow(new Object[]{skdbrg, snmbrg, sjum, smod, shar});
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null,
                    "Gk bisa nampilin data bos"+e);
        }
    }//GEN-LAST:event_tfcarikdActionPerformed

    private void tfcarinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcarinamaActionPerformed
        String carinama = tfcarinama.getText();
        Object[] baris = {"Kode Barang", "Nama Barang", "Jumlah", "Modal", "Harga"};
        tabmodel = new DefaultTableModel(null, baris);
        tbarang.setModel(tabmodel);
        String sql = "select * from barang where nama_barang LIKE '%"+carinama+"%'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String skdbrg = hasil.getString("kode_barang");
                String snmbrg = hasil.getString("nama_barang");
                int sjum = hasil.getInt("jumlah");
                int smod = hasil.getInt("modal");
                int shar = hasil.getInt("harga");
                tabmodel.addRow(new Object[]{skdbrg, snmbrg, sjum, smod, shar});
            }
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null,
                    "Gk bisa nampilin data bos"+e);
        }
    }//GEN-LAST:event_tfcarinamaActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        if (edittombol == 0){
            tfnama.setEnabled(true);
            tfjumlah.setEnabled(true);
            tfmodal.setEnabled(true);
            tfharga.setEnabled(true);
            jbclear.setEnabled(true);
            jbsave.setEnabled(true);
            edittombol = 1;
        } else {
            tfnama.setEnabled(false);
            tfjumlah.setEnabled(false);
            tfmodal.setEnabled(false);
            tfharga.setEnabled(false);
            jbclear.setEnabled(false);
            jbsave.setEnabled(false);
            kosong();
            edittombol = 0;
            
        }
    }//GEN-LAST:event_btneditActionPerformed

    private void tbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbarangMouseClicked
        int bar = tbarang.getSelectedRow();
        ekode = tabmodel.getValueAt(bar, 0).toString();
        enama = tabmodel.getValueAt(bar, 1).toString();
        ejumlah = tabmodel.getValueAt(bar, 2).toString();
        emodal = tabmodel.getValueAt(bar, 3).toString();
        eharga = tabmodel.getValueAt(bar, 4).toString();
        if (edittombol == 1){
            tfkode.setText(ekode);
            tfnama.setText(enama);
            tfjumlah.setText(ejumlah);
            tfmodal.setText(emodal);
            tfharga.setText(eharga);
        } else {
            if (editprompt == 0){
                JOptionPane.showMessageDialog(null,
                    "Klik Tombol Edit untuk meng-enable bagan edit");
                editprompt = 1;
            }
        }
        
        
    }//GEN-LAST:event_tbarangMouseClicked

    private void jbdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbdeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,
                "Anda yakin ingin menghapus data?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "delete from barang where " + "kode_barang='"+ekode+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,
                       "Data berhasil dihapus");
                dataTable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_jbdeleteActionPerformed

    private void jbclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbclearActionPerformed
        kosong();
    }//GEN-LAST:event_jbclearActionPerformed

    private void jbsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsaveActionPerformed
        String s_jum = tfjumlah.getText();
        int jum = Integer.parseInt(s_jum);
        if(jum >= 0){
            try{
                String sql = "update barang set nama_barang=?,"+" jumlah=?,"+" modal=?,"+" harga=?"+" where kode_barang='"+tfkode.getText()+"'";
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, tfnama.getText());
                int jumlah = Integer.valueOf(tfjumlah.getText());
                stat.setInt(2, jumlah);
                int modal = Integer.valueOf(tfmodal.getText());
                stat.setInt(3, modal);
                int harga = Integer.valueOf(tfharga.getText());
                stat.setInt(4, harga);

                stat.executeUpdate();
                JOptionPane.showMessageDialog(null,
                        "Data Berasil disimpan");
                kosong();
                dataTable();

            }
            catch(SQLException e) {
                JOptionPane.showMessageDialog(null,
                        "Data gagal diubah"+e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nilai Jumlah Tidak Boleh Negatif");
        }
    }//GEN-LAST:event_jbsaveActionPerformed

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanMouseClicked

    private void jasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jasaMouseClicked
        try {
            new daftarjasa().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jasaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new daftarbarang().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(daftarbarang.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JMenuItem gbarang;
    private javax.swing.JMenuItem gbaru;
    private javax.swing.JMenu gudang;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jasa;
    private javax.swing.JButton jbclear;
    private javax.swing.JButton jbdelete;
    private javax.swing.JButton jbsave;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JTable tbarang;
    private javax.swing.JMenuItem tbaru;
    private javax.swing.JMenuItem tdaftar;
    private javax.swing.JTextField tfcarikd;
    private javax.swing.JTextField tfcarinama;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkode;
    private javax.swing.JTextField tfmodal;
    private javax.swing.JTextField tfnama;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
