/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontrol.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import javax.servlet.ServletOutputStream;

/**
 *
 * @author Bayu
 */
public class home extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    
    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITLE = new javax.swing.JLabel();
        jbbulan = new javax.swing.JButton();
        jbketersediaan = new javax.swing.JButton();
        TITLE1 = new javax.swing.JLabel();
        TITLE2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        gudang = new javax.swing.JMenu();
        gbaru = new javax.swing.JMenuItem();
        gbarang = new javax.swing.JMenuItem();
        jasa = new javax.swing.JMenu();
        transaksi = new javax.swing.JMenu();
        tbaru = new javax.swing.JMenuItem();
        tdaftar = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kendali Motor Transaksi & Inventori");
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(250, 140));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITLE.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        TITLE.setText("LAPORAN");
        getContentPane().add(TITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 250, 60));

        jbbulan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/bulanansmall.png"))); // NOI18N
        jbbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbulanActionPerformed(evt);
            }
        });
        getContentPane().add(jbbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 140, -1));

        jbketersediaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/reportsmall.png"))); // NOI18N
        jbketersediaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbketersediaanActionPerformed(evt);
            }
        });
        getContentPane().add(jbketersediaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 140, -1));

        TITLE1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TITLE1.setText("Laporan Transaksi");
        getContentPane().add(TITLE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 220, 60));

        TITLE2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TITLE2.setText("Laporan Ketersediaan");
        getContentPane().add(TITLE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 260, 60));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/GreyBackground.png"))); // NOI18N
        bg.setPreferredSize(new java.awt.Dimension(628, 395));
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 454));

        gudang.setText("Gudang");

        gbaru.setText("Barang Baru");
        gbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbaruActionPerformed(evt);
            }
        });
        gudang.add(gbaru);

        gbarang.setText("Daftar Barang");
        gbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbarangActionPerformed(evt);
            }
        });
        gudang.add(gbarang);

        menubar.add(gudang);

        jasa.setText("Jasa");
        jasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jasaMouseClicked(evt);
            }
        });
        menubar.add(jasa);

        transaksi.setText("Transaksi");

        tbaru.setText("Transaksi Baru");
        tbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbaruActionPerformed(evt);
            }
        });
        transaksi.add(tbaru);

        tdaftar.setText("Daftar Transaksi");
        tdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdaftarActionPerformed(evt);
            }
        });
        transaksi.add(tdaftar);

        menubar.add(transaksi);

        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        menubar.add(laporan);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbarangActionPerformed
        try {
            new daftarbarang().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_gbarangActionPerformed

    private void gbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbaruActionPerformed
        new inputbarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_gbaruActionPerformed

    private void tdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdaftarActionPerformed
        try {
            new daftartransaksi().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_tdaftarActionPerformed

    private void tbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbaruActionPerformed
        new transaksibaru().setVisible(true);
        dispose();
    }//GEN-LAST:event_tbaruActionPerformed

    private void jbbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbulanActionPerformed
        try {               
            JasperReport jasperReport = null;
            InputStream path=this.getClass().getResourceAsStream("reportbulan.jrxml");   
            InputStream logo = this.getClass().getResourceAsStream("pistonseditan3small60.jpg"); //"src/icon/pistonseditan3small60.jpg"
            JasperPrint jasperPrint = null;
            jasperReport = JasperCompileManager.compileReport(path);
            HashMap parameters = new HashMap();
            //JasperReport subReport = JasperCompileManager.compileReport(this.getClass().getResourceAsStream("reportbulan_subreport1.jrxml"));
            InputStream SubReport = this.getClass().getResourceAsStream("reportbulan_subreport1.jasper");
            parameters.put("SubReport", SubReport);
            parameters.put("LOGO", logo);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbbulanActionPerformed

    private void jbketersediaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbketersediaanActionPerformed
        try {               
            JasperReport jasperReport = null;
            InputStream path=this.getClass().getResourceAsStream("report_ketersediaan.jrxml");  
            InputStream logo = this.getClass().getResourceAsStream("pistonseditan3small60.jpg");
            JasperPrint jasperPrint = null;
            jasperReport = JasperCompileManager.compileReport(path);
            HashMap parameters = new HashMap();
            parameters.put("LOGO", logo);
            jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);
            JasperViewer.viewReport(jasperPrint,false);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbketersediaanActionPerformed

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanMouseClicked

    private void jasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jasaMouseClicked
        try {
            new daftarjasa().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jasaMouseClicked

    String ReportPath="D:/ProgramBayu/visualbengkel/src/ui/testreport.jrxml";

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TITLE;
    private javax.swing.JLabel TITLE1;
    private javax.swing.JLabel TITLE2;
    private javax.swing.JLabel bg;
    private javax.swing.JMenuItem gbarang;
    private javax.swing.JMenuItem gbaru;
    private javax.swing.JMenu gudang;
    private javax.swing.JMenu jasa;
    private javax.swing.JButton jbbulan;
    private javax.swing.JButton jbketersediaan;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem tbaru;
    private javax.swing.JMenuItem tdaftar;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
