/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontrol.koneksi;

/**
 *
 * @author Bayu
 */
public class inputbarang extends javax.swing.JFrame {
    private final Connection conn = new koneksi().connect();
    String id_merk="";
    String id_tipe="";
    /**
     * Creates new form inputbarang
     */
    public inputbarang() {
        initComponents();
        isicombobox();
    }

    private void kosong(){
        tfkdbrg.setText("");
        tfnmbrg.setText("");
        tfjumlah.setText("");
        tfmodal.setText("");
        tfharga.setText("");
        cb_merk.setSelectedItem(0);
        cb_tipe.setSelectedItem(0);
    }
    private void kosong_merk(){
        tf_id_merk.setText("");
        tf_nm_merk.setText("");
    }
    private void kosong_tipe(){
        tf_id_tipe.setText("");
        tf_nm_tipe.setText("");
    }
    private void isicombobox(){
        cb_merk.removeAllItems();
        cb_tipe.removeAllItems();
        try{
            String sql = "select nama_merk from merk";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            cb_merk.addItem("");
            while(hasil.next()){
                String nm_merk = hasil.getString("nama_merk");
                cb_merk.addItem(nm_merk);
            }
            
            String sqltipe = "select nama_tipe from tipe_barang";
            ResultSet hasiltipe = stat.executeQuery(sqltipe);
            cb_tipe.addItem("");
            while(hasiltipe.next()){
                String nm_tipe = hasiltipe.getString("nama_tipe");
                cb_tipe.addItem(nm_tipe);
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void getid(){
        String nm_merk = (String)cb_merk.getSelectedItem();
        String nm_tipe = (String)cb_tipe.getSelectedItem();
        try{
            String sql = "select id_merk from merk where nama_merk='"+nm_merk+"'";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                id_merk = hasil.getString("id_merk");
            }
            String sql_tipe = "select id_tipe from tipe_barang where nama_tipe='"+nm_tipe+"'";
            java.sql.Statement stat_tipe = conn.createStatement();
            ResultSet hasil_tipe = stat.executeQuery(sql_tipe);
            while(hasil_tipe.next()){
                id_tipe = hasil_tipe.getString("id_tipe");
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void isikodebrg(){
        String kode_brg = "";
        kode_brg = id_merk + id_tipe;
        int hasil_count = 0;
        try{
            String check_sql = "select kode_barang from barang where kode_barang LIKE '"+kode_brg+"%'";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil_check = stat.executeQuery(check_sql);
            while(hasil_check.next()){
                hasil_count++;
            }
            hasil_count++;
            if(hasil_count < 10){
                kode_brg = kode_brg+"00"+hasil_count;
            }else if(hasil_count > 9 && hasil_count < 100){
                kode_brg = kode_brg+"0"+hasil_count;
            } else if (hasil_count > 99){
                kode_brg = kode_brg+hasil_count;
            }
            
            tfkdbrg.setText(kode_brg);
            
            if((id_merk.equals(""))||(id_tipe.equals(""))){
                tfkdbrg.setText("");
            }
            String nm_merk = (String)cb_merk.getSelectedItem();
            String nm_tipe = (String)cb_tipe.getSelectedItem();
            tfnmbrg.setText(nm_tipe+" "+nm_merk);
            
        } catch(SQLException ex) {
                JOptionPane.showMessageDialog(null,ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfkdbrg = new javax.swing.JTextField();
        tfnmbrg = new javax.swing.JTextField();
        tfjumlah = new javax.swing.JTextField();
        tfmodal = new javax.swing.JTextField();
        tfharga = new javax.swing.JTextField();
        bclear = new javax.swing.JButton();
        bsave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cb_merk = new javax.swing.JComboBox<>();
        cb_tipe = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_id_merk = new javax.swing.JTextField();
        tf_nm_merk = new javax.swing.JTextField();
        jb_merk_clear = new javax.swing.JButton();
        jb_merk_save = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tf_id_tipe = new javax.swing.JTextField();
        tf_nm_tipe = new javax.swing.JTextField();
        jb_tipe_clear = new javax.swing.JButton();
        jb_tipe_save = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        gudang = new javax.swing.JMenu();
        gbaru = new javax.swing.JMenuItem();
        gbarang = new javax.swing.JMenuItem();
        jasa = new javax.swing.JMenu();
        transaksi = new javax.swing.JMenu();
        tbaru = new javax.swing.JMenuItem();
        tdaftar = new javax.swing.JMenuItem();
        laporan = new javax.swing.JMenu();

        jLabel5.setText("jLabel5");

        jLabel8.setText("Harga Jual");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pengisian Barang Baru");
        setLocation(new java.awt.Point(250, 140));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Masukan Barang Baru");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 300, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Nama Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 100, 24));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Jumlah");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 24));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Modal");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 100, 24));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Harga Jual");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 100, 24));

        tfkdbrg.setEditable(false);
        jPanel1.add(tfkdbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 90, 24));
        jPanel1.add(tfnmbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 180, 24));
        jPanel1.add(tfjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 90, 24));
        jPanel1.add(tfmodal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 180, 24));
        jPanel1.add(tfharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 180, 24));

        bclear.setText("Clear");
        bclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclearActionPerformed(evt);
            }
        });
        jPanel1.add(bclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        bsave.setText("Save");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });
        jPanel1.add(bsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Kode Barang ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 24));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 410, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel16.setText("Nama Merek");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel17.setText("Nama Tipe");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        cb_merk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_merkActionPerformed(evt);
            }
        });
        jPanel1.add(cb_merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 150, -1));

        cb_tipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipeActionPerformed(evt);
            }
        });
        jPanel1.add(cb_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 410, 470));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Merek Baru");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("ID Merek");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setText("Nama Merek");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel2.add(tf_id_merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 60, -1));
        jPanel2.add(tf_nm_merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        jb_merk_clear.setText("Clear");
        jb_merk_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_merk_clearActionPerformed(evt);
            }
        });
        jPanel2.add(jb_merk_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jb_merk_save.setText("Save");
        jb_merk_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_merk_saveActionPerformed(evt);
            }
        });
        jPanel2.add(jb_merk_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 320, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Tipe Baru");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel14.setText("ID Tipe");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Nama Tipe");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));
        jPanel2.add(tf_id_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 60, -1));
        jPanel2.add(tf_nm_tipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 150, -1));

        jb_tipe_clear.setText("Clear");
        jb_tipe_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_tipe_clearActionPerformed(evt);
            }
        });
        jPanel2.add(jb_tipe_clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jb_tipe_save.setText("Save");
        jb_tipe_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_tipe_saveActionPerformed(evt);
            }
        });
        jPanel2.add(jb_tipe_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 320, 470));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/GreyBackground.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 820, 550));

        gudang.setText("Gudang");

        gbaru.setText("Barang Baru");
        gbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbaruActionPerformed(evt);
            }
        });
        gudang.add(gbaru);

        gbarang.setText("Daftar Barang");
        gbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gbarangActionPerformed(evt);
            }
        });
        gudang.add(gbarang);

        menubar.add(gudang);

        jasa.setText("Jasa");
        jasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jasaMouseClicked(evt);
            }
        });
        menubar.add(jasa);

        transaksi.setText("Transaksi");

        tbaru.setText("Transaksi Baru");
        tbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbaruActionPerformed(evt);
            }
        });
        transaksi.add(tbaru);

        tdaftar.setText("Daftar Transaksi");
        tdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdaftarActionPerformed(evt);
            }
        });
        transaksi.add(tdaftar);

        menubar.add(transaksi);

        laporan.setText("Laporan");
        laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laporanMouseClicked(evt);
            }
        });
        menubar.add(laporan);

        setJMenuBar(menubar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclearActionPerformed
        kosong();
    }//GEN-LAST:event_bclearActionPerformed

    private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
        String sql = "insert into barang values (?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tfkdbrg.getText());
            stat.setString(2, tfnmbrg.getText());
            int tempint;
            if(!(tfjumlah.getText().equals(""))){
                tempint = Integer.parseInt(tfjumlah.getText());
                stat.setInt(3, tempint);
            }
            if(!(tfmodal.getText().equals(""))){
                tempint = Integer.parseInt(tfmodal.getText());
                stat.setInt(4, tempint);
            }
            if(!(tfharga.getText().equals(""))){
                tempint = Integer.parseInt(tfharga.getText());
                stat.setInt(5, tempint);
            }
            stat.setString(6, id_merk);
            stat.setString(7, id_tipe);
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,
                    "Data Berasil disimpan");
            kosong();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Pastikan semua kolom diisi dengan benar");
        }
    }//GEN-LAST:event_bsaveActionPerformed

    private void gbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbarangActionPerformed
        try {
            new daftarbarang().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_gbarangActionPerformed

    private void gbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gbaruActionPerformed
        new inputbarang().setVisible(true);
        dispose();
    }//GEN-LAST:event_gbaruActionPerformed

    private void tdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdaftarActionPerformed
        try {
            new daftartransaksi().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_tdaftarActionPerformed

    private void tbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbaruActionPerformed
        new transaksibaru().setVisible(true);
        dispose();
    }//GEN-LAST:event_tbaruActionPerformed

    private void laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laporanMouseClicked
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_laporanMouseClicked

    private void jasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jasaMouseClicked
        try {
            new daftarjasa().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jasaMouseClicked

    private void jb_merk_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_merk_clearActionPerformed
        kosong_merk();
    }//GEN-LAST:event_jb_merk_clearActionPerformed

    private void jb_merk_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_merk_saveActionPerformed
        String sql = "insert into merk values (?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_id_merk.getText());
            stat.setString(2, tf_nm_merk.getText());
                       
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,
                    "Data Berasil disimpan");
            kosong();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,
                    "ID Merk '"+tf_id_merk.getText()+"' sudah terdaftar");
        }
        kosong_merk();
        isicombobox();
    }//GEN-LAST:event_jb_merk_saveActionPerformed

    private void jb_tipe_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_tipe_clearActionPerformed
       kosong_tipe();
    }//GEN-LAST:event_jb_tipe_clearActionPerformed

    private void jb_tipe_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_tipe_saveActionPerformed
        String sql = "insert into tipe_barang values (?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_id_tipe.getText());
            stat.setString(2, tf_nm_tipe.getText());
                       
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,
                    "Data Berasil disimpan");
            kosong();
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,
                    "ID Tipe '"+tf_id_tipe.getText()+"' sudah terdaftar");
        }
        kosong_tipe();
        isicombobox();
    }//GEN-LAST:event_jb_tipe_saveActionPerformed

    private void cb_tipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipeActionPerformed
        getid();
        isikodebrg();
    }//GEN-LAST:event_cb_tipeActionPerformed

    private void cb_merkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_merkActionPerformed
        getid();
        isikodebrg();
    }//GEN-LAST:event_cb_merkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputbarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputbarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclear;
    private javax.swing.JButton bsave;
    private javax.swing.JComboBox<String> cb_merk;
    private javax.swing.JComboBox<String> cb_tipe;
    private javax.swing.JMenuItem gbarang;
    private javax.swing.JMenuItem gbaru;
    private javax.swing.JMenu gudang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu jasa;
    private javax.swing.JButton jb_merk_clear;
    private javax.swing.JButton jb_merk_save;
    private javax.swing.JButton jb_tipe_clear;
    private javax.swing.JButton jb_tipe_save;
    private javax.swing.JMenu laporan;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem tbaru;
    private javax.swing.JMenuItem tdaftar;
    private javax.swing.JTextField tf_id_merk;
    private javax.swing.JTextField tf_id_tipe;
    private javax.swing.JTextField tf_nm_merk;
    private javax.swing.JTextField tf_nm_tipe;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkdbrg;
    private javax.swing.JTextField tfmodal;
    private javax.swing.JTextField tfnmbrg;
    private javax.swing.JMenu transaksi;
    // End of variables declaration//GEN-END:variables
}
